---
title: "Moving Beyond Linearity (i)"
author: "Simon"
date: "2023-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

```{r}
my.func <- function(x){
  (x <= 0) * (-10 - 5 * x) +
    (x > 0) * (10 + (x + 5) * (x - 1.6) ^ 2 * (x + 1) ^ 3 * sin(6.5 * x))
}

X.grid.1 <- seq(from = -2, to = 0, by = 0.01)
Y.grid.1 <- my.func(X.grid.1)
X.grid.2 <- seq(from = 0.01, to = 2, by = 0.01)
Y.grid.2 <- my.func(X.grid.2)

plot(X.grid.1, Y.grid.1, type = "l", lwd = 3, col = "blue", 
     xlab = "X", ylab = "Y",
     xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
```

```{r}
set.seed(123)
N <- 1200
X <- rnorm(n = N, mean = 0, sd = 0.9)
U <- rnorm(n = N, mean = 0, sd = 10)
Y <- my.func(X) + U
```

```{r}
plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
```

```{r}
fit.1 <- lm(Y ~ X)
summary(fit.1)

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
abline(fit.1, lwd = 3, col = "red")
```

```{r}
fit.2 <- lm(Y ~ X + I(X ^ 2))  # fit.2 <- lm(Y ~ X + X ^ 2) does not work.
summary(fit.1)

fit.2 <- lm(Y ~ poly(X, 2, raw = T))
summary(fit.2)

X.lims = range(X)
X.grid <- seq(from = X.lims[1], to = X.lims[2], length.out = 500)
predict.fit.2 <- predict(fit.2, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.2, lwd = 3, col = "red")
```

```{r}
fit.2.o <- lm(Y ~ poly(X, 2))
summary(fit.2.o)

t(poly(X, 2)) %*% poly(X, 2)
t(poly(X, 2, raw = T)) %*% poly(X, 2, raw = T)

predict.fit.2.o <- predict(fit.2.o, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.2.o, lwd = 3, col = "red")
```

```{r}
fit.3 <- lm(Y ~ poly(X, 3, raw = T))
predict.fit.3 <- predict(fit.3, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.3, lwd = 3, col = "red")
```

```{r}
fit.4 <- lm(Y ~ poly(X, 4, raw = T))
predict.fit.4 <- predict(fit.4, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.4, lwd = 3, col = "red")
```

```{r}
fit.10 <- lm(Y ~ poly(X, 10, raw = T))
predict.fit.10 <- predict(fit.10, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.10, lwd = 3, col = "red")
```

```{r}
fit.15 <- lm(Y ~ poly(X, 15, raw = T))
predict.fit.15 <- predict(fit.15, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.15, lwd = 3, col = "red")
```

```{r}
fit.25 <- lm(Y ~ poly(X, 25, raw = T))
predict.fit.25 <- predict(fit.25, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.25, lwd = 3, col = "red")
```

```{r}
fit.30 <- lm(Y ~ poly(X, 30, raw = T))
predict.fit.30 <- predict(fit.30, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.30, lwd = 3, col = "red")
```

```{r}
fit.c.2 <- lm(Y ~ cut(X, 2))
summary(fit.c.2)

X.lims = range(X)
X.grid <- seq(from = X.lims[1], to = X.lims[2], length.out = 500)
predict.fit.c.2 <- predict(fit.c.2, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.c.2, lwd = 3, col = "red")
```

```{r}
fit.c.10 <- lm(Y ~ cut(X, 10))
summary(fit.c.10)
predict.fit.c.10 <- predict(fit.c.10, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.c.10, lwd = 3, col = "red")
```

```{r}
# Spline
library("splines")

fit.bs.10 <- lm(Y ~ bs(X, df = 10, degree = 3)) # bs = basis splines / B-splines
summary(fit.bs.10)
predict.fit.bs.10 <- predict(fit.bs.10, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.bs.10, lwd = 3, col = "red")
```

```{r}
fit.ns.10 <- lm(Y ~ ns(X, df = 10)) # ns = natural splines
summary(fit.ns.10)
predict.fit.ns.10 <- predict(fit.ns.10, newdata = list(X = X.grid))

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, predict.fit.ns.10, lwd = 3, col = "red")
```

```{r}
Z <- seq(from = 0, to = 1, by = 0.001)
Z.bs <- bs(Z, df = 6, degree = 3)
Z.ns <- ns(Z, df = 6)

par(mfrow = c(2, 3))
plot(Z, Z.bs[, 1])
plot(Z, Z.bs[, 2])
plot(Z, Z.bs[, 3])
plot(Z, Z.bs[, 4])
plot(Z, Z.bs[, 5])
plot(Z, Z.bs[, 6])

par(mfrow = c(2, 3))
plot(Z, Z.ns[, 1])
plot(Z, Z.ns[, 2])
plot(Z, Z.ns[, 3])
plot(Z, Z.ns[, 4])
plot(Z, Z.ns[, 5])
plot(Z, Z.ns[, 6])
```
