---
title: "Trees, Random Forests, and Gradient Boosting"
author: "Simon"
date: "2023-01-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

# Curse of Dimensionality

```{r}
my.func <- function(x){
  (x <= 0) * (-10 - 5 * x) +
    (x > 0) * (10 + (x + 5) * (x - 1.6) ^ 2 * (x + 1) ^ 3 * sin(6.5 * x))
}

X.grid.1 <- seq(from = -2, to = 0, by = 0.01)
Y.grid.1 <- my.func(X.grid.1)
X.grid.2 <- seq(from = 0.01, to = 2, by = 0.01)
Y.grid.2 <- my.func(X.grid.2)

plot(X.grid.1, Y.grid.1, type = "l", lwd = 3, col = "blue", 
     xlab = "X", ylab = "Y",
     xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
```

```{r}
set.seed(123)
N <- 1200
X <- rnorm(n = N, mean = 0, sd = 0.9)
U <- rnorm(n = N, mean = 0, sd = 10)
Y <- my.func(X) + U

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
```

```{r}
X.lims = range(X)
X.grid <- seq(from = X.lims[1], to = X.lims[2], length.out = 500)

library(FNN)

knn.1 <- knn.reg(train = as.matrix(X), test = as.matrix(X.grid), y = Y, k = 40)

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, knn.1$pred, lwd = 3, col = "red")
```

```{r}
W <- rnorm(n = N, mean = 0, sd = 0.9)

# Y(i) = F(X(i)) + U(i)
# But the econometrician does not know the tree data generating process,
# and specifies the model: Y(i) = G(X(i) + W(i)) + error(i)

W.grid <- rep(0, 500)
X.W <- cbind(X, W)
X.W.grid <- cbind(X.grid, W.grid)

knn.2 <- knn.reg(train = X.W, test = X.W.grid, y = Y, k = 40)

plot(X, Y, xlim = c(-2, 2), ylim = c(-50, 50))
lines(X.grid.1, Y.grid.1, lwd = 3, col = "blue")
lines(X.grid.2, Y.grid.2, lwd = 3, col = "blue")
lines(X.grid, knn.2$pred, lwd = 3, col = "red")
```
