---
title: "Neural Networks"
author: "Simon"
date: "2023-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

```{r}
library(neuralnet)
library(MASS)

data <- Boston
set.seed(500)
index <- sample(1: nrow(data), round(0.75 * nrow(data)))
train <- data[index,]
test <- data[-index,]
```

```{r}
maxs <- apply(data, 2, max)
mins <- apply(data, 2, min)
scaled <- as.data.frame(scale(data, center = mins, scale = maxs - mins))
train_ <- scaled[index,]
test_ <- scaled[-index,]
```

```{r}
lm.fit <- lm(medv ~ ., data = train)
summary(lm.fit)
pr.lm <- predict(lm.fit, test)
MSE.lm <- sum((pr.lm - test$medv) ^ 2) / nrow(test)
```

```{r}
library(neuralnet)

set.seed(500)
n <- names(train_)
f <- as.formula(paste("medv ~", paste(n[!n %in% "medv"], collapse = " + ")))
nn <- neuralnet(f, data = train_, hidden = c(5, 3), linear.output = T)

plot(nn)

pr.nn <- compute(nn, test_[, 1: 13])
pr.nn_ <- pr.nn$net.result * (max(data$medv) - min(data$medv)) + min(data$medv)
MSE.nn <- sum((pr.nn_ - test$medv) ^ 2) / nrow(test)

print(paste(MSE.lm, MSE.nn))
```
